### ISSUE TITLE
Add support for Videos and Audio Recordings

### ISSUE THREAD

**Issue by jpbronsted** [DoctorPepper/CameroonApp#4]
Add video and audio recording activities. Ideally, documents of all types are bundled into some generic object and sent to a document submission subsystem that sends it to the server/database.

**Comment by jpbronsted** [comment]
We weren't able to completely finish this in Sprint 2, so we're moving it to Sprint 3.

**Comment by DoctorPepper** [comment]
I'll work on the audio recording feature.
