### ISSUE TITLE
Self-Destruct Button

### ISSUE THREAD

**Issue by jpbronsted** [DoctorPepper/CameroonApp#8]
Add a UI element that allows a user to quickly and securely self-destruct the app, removing all traces of it from the device. This could be a button in the document selection activity; perhaps putting in the passcode activity is a better idea since it'll be even more accessible.

To admins: please file this as a Sprint 3 issue.

**Comment by DoctorPepper** [comment]
We realized during this sprint that this issue was not worth perusing -- there was no security advantages to deleting the app inside the app. Therefore, we will just have our users delete the app normally.
